In [11]:
#NUMPY

import numpy as np
my_list = [1,2,3]
print(type(my_list))
np.array(my_list)
myarray = np.array(my_list)
print(type(myarray))
mylist2 = [[1,2,3],[4,5,6],[7,8,9]]
print(mylist2)
mylistarray = np.array(mylist2)
print(mylistarray)
myarraylist = np.arange(0,10)
print(myarraylist)
myarraylist1 = np.arange(0,100,20)#step up by 20
print(myarraylist1)
zeronum = np.zeros(5)
print(zeronum)
zeronum1 = np.zeros((5,5))
print(zeronum1)#like this we have ones 
#linspace

<class 'list'>
<class 'numpy.ndarray'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[ 0 20 40 60 80]
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [33]:
print(np.linspace(0,10,23))
print(np.eye(5))#-->Identiy matix
print(np.random.rand(5,2))#Creating numbers with under 1 with array
print(np.random.randn(5))
print(np.random.randint(0,10),(1,2))#Creating Random integers
np.random.seed(42)
print("Random numbers in Cell 1:", np.random.rand(3))

np.random.seed(10)
print("Random numbers in Cell 2:", np.random.rand(3))

print("Random numbers in Cell 3:", np.random.rand(3))

[ 0.          0.45454545  0.90909091  1.36363636  1.81818182  2.27272727
  2.72727273  3.18181818  3.63636364  4.09090909  4.54545455  5.
  5.45454545  5.90909091  6.36363636  6.81818182  7.27272727  7.72727273
  8.18181818  8.63636364  9.09090909  9.54545455 10.        ]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.19806286 0.76053071]
 [0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]]
[-0.96506567  1.02827408  0.22863013  0.44513761 -1.13660221]
6 (1, 2)
Random numbers in Cell 1: [0.37454012 0.95071431 0.73199394]
Random numbers in Cell 2: [0.77132064 0.02075195 0.63364823]
Random numbers in Cell 3: [0.74880388 0.49850701 0.22479665]


In [44]:
ranr = np.random.randint(0,25,20)
print(ranr)
print(ranr.reshape(5,4))
print(ranr.min())
print(ranr.max())
print(ranr.argmax())

[15 19 17 18 21 14 16 10 17  0 17  9 16  9 12 18 17 17 16  0]
[[15 19 17 18]
 [21 14 16 10]
 [17  0 17  9]
 [16  9 12 18]
 [17 17 16  0]]
0
21
4


In [48]:
import numpy as n
myarray = n.linspace(0,10,101)
print(myarray)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]


***NUMPY INDEXING AND SLICING***

In [50]:
import numpy as np

# Create a 1D NumPy array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Basic indexing
print(arr[0])  # Access the first element (10)
print(arr[5])  # Access the sixth element (60)
print(arr[-1]) # Access the last element (100)
print(arr[-3]) # Access the third-to-last element (80)

# Slicing
print(arr[1:5])    # Elements from index 1 up to (but not including) 5: [20 30 40 50]
print(arr[:4])     # Elements from the beginning up to (but not including) 4: [10 20 30 40]
print(arr[3:])     # Elements from index 3 to the end: [40 50 60 70 80 90 100]
print(arr[::2])    # Every other element: [10 30 50 70 90]
print(arr[1::2])   # Every other element, starting from index 1: [20 40 60 80 100]
print(arr[::-1])   # Reverse the array: [100 90 80 70 60 50 40 30 20 10]

# Combining indexing and slicing
print(arr[2:7][1:3]) # Slice from index 2 to 7, then slice the result from 1 to 3: [40 50]

# Modifying elements using indexing and slicing
arr[0] = 1000       # Change the first element
arr[2:5] = [300, 400, 500] # Change elements from index 2 to 5
print(arr)

# Using boolean indexing
bool_index = arr > 500
print(arr[bool_index]) # Print elements greater than 500

# Using fancy indexing (array of indices)
indices = [1, 4, 7]
print(arr[indices]) # Print elements at indices 1, 4, and 7

10
60
100
80
[20 30 40 50]
[10 20 30 40]
[ 40  50  60  70  80  90 100]
[10 30 50 70 90]
[ 20  40  60  80 100]
[100  90  80  70  60  50  40  30  20  10]
[40 50]
[1000   20  300  400  500   60   70   80   90  100]
[1000]
[ 20 500  80]


In [52]:
import numpy as np

# Create a 2D NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original array:\n", arr)

# Basic indexing
print("\nIndexing:")
print("arr[0, 1]:", arr[0, 1])  # Element at row 0, column 1 (2)
print("arr[1, 2]:", arr[1, 2])  # Element at row 1, column 2 (6)
print("arr[-1, -1]:", arr[-1, -1]) # Last element (9)
print("arr[1]:", arr[1])       # Entire row at index 1 ([4 5 6])

# Slicing
print("\nSlicing:")
print("arr[0:2, 1:3]:\n", arr[0:2, 1:3])  # Rows 0 and 1, columns 1 and 2
print("arr[:, 0]:", arr[:, 0])      # All rows, first column
print("arr[1, :]:", arr[1, :])      # Second row, all columns
print("arr[:, :2]:\n", arr[:, :2])      # All rows, first two columns
print("arr[:-1, :-1]:\n", arr[:-1, :-1]) # All rows except last, all columns except last

# Combining indexing and slicing
print("\nCombining:")
print("arr[0:2, 0:2][1, 1]:", arr[0:2, 0:2][1, 1]) # Slice then index (5)

# Modifying elements
print("\nModifying:")
arr_modified = arr.copy() # Important: Create a copy to avoid modifying the original
print("arr_modified[0, 0] = 100")
arr_modified[0, 0] = 100
print("arr_modified:\n", arr_modified)

print("\narr_modified[1:3, 1:3] = [[50, 60], [80, 90]]")
arr_modified[1:3, 1:3] = [[50, 60], [80, 90]]
print("arr_modified:\n", arr_modified)


# Boolean indexing
print("\nBoolean indexing:")
bool_index = arr > 5
print("bool_index:\n", bool_index)
print("arr[bool_index]:", arr[bool_index])

# Fancy indexing
print("\nFancy indexing:")
indices = [0, 2]  # Row indices
indices2 = [1,2] # column indices
print("arr[[0, 2], [1, 2]]:", arr[[0, 2], [1, 2]]) # Elements at (0,1) and (2,2)
print("arr[[0, 2], :]:\n", arr[[0, 2], :]) # Rows 0 and 2, all columns
print("arr[:, [1, 2]]:\n", arr[:, [1, 2]]) # All rows, columns 1 and 2

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Indexing:
arr[0, 1]: 2
arr[1, 2]: 6
arr[-1, -1]: 9
arr[1]: [4 5 6]

Slicing:
arr[0:2, 1:3]:
 [[2 3]
 [5 6]]
arr[:, 0]: [1 4 7]
arr[1, :]: [4 5 6]
arr[:, :2]:
 [[1 2]
 [4 5]
 [7 8]]
arr[:-1, :-1]:
 [[1 2]
 [4 5]]

Combining:
arr[0:2, 0:2][1, 1]: 5

Modifying:
arr_modified[0, 0] = 100
arr_modified:
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]]

arr_modified[1:3, 1:3] = [[50, 60], [80, 90]]
arr_modified:
 [[100   2   3]
 [  4  50  60]
 [  7  80  90]]

Boolean indexing:
bool_index:
 [[False False False]
 [False False  True]
 [ True  True  True]]
arr[bool_index]: [6 7 8 9]

Fancy indexing:
arr[[0, 2], [1, 2]]: [2 9]
arr[[0, 2], :]:
 [[1 2 3]
 [7 8 9]]
arr[:, [1, 2]]:
 [[2 3]
 [5 6]
 [8 9]]


In [54]:
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
total_rolls_over_two = dice_rolls > 2
dice_rolls = dice_rolls[total_rolls_over_two]
print(len(dice_rolls))

19


In [1]:
#Numpy operations
import numpy as np

import numpy as np

# Creating arrays
arr1 = np.array([1, 2, 3, 4, 5])  # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array (matrix)
arr3 = np.zeros((3, 4))  # Array of zeros
arr4 = np.ones((2, 2))  # Array of ones
arr5 = np.arange(10)  # Array from 0 to 9
arr6 = np.linspace(0, 1, 5)  # Array of 5 evenly spaced numbers from 0 to 1

print("arr1:", arr1)
print("arr2:\n", arr2)
print("arr3:\n", arr3)
print("arr4:\n", arr4)
print("arr5:", arr5)
print("arr6:", arr6)

# Array attributes
print("\nAttributes:")
print("arr1.ndim:", arr1.ndim)  # Number of dimensions
print("arr2.shape:", arr2.shape)  # Shape (rows, columns)
print("arr1.size:", arr1.size)  # Total number of elements
print("arr1.dtype:", arr1.dtype)  # Data type of elements

# Basic operations
print("\nBasic Operations:")
print("arr1 + 5:", arr1 + 5)  # Element-wise addition
print("arr1 * 2:", arr1 * 2)  # Element-wise multiplication
print("arr1 ** 2:", arr1 ** 2)  # Element-wise exponentiation
print("np.sin(arr1):", np.sin(arr1)) # Element-wise sine calculation

# Aggregation functions
print("\nAggregation:")
print("np.sum(arr1):", np.sum(arr1))  # Sum of all elements
print("np.mean(arr1):", np.mean(arr1))  # Mean of all elements
print("np.max(arr2):", np.max(arr2))  # Maximum element
print("np.min(arr2):", np.min(arr2))  # Minimum element
print("np.std(arr1):", np.std(arr1)) # Standard deviation

# Matrix operations (for 2D arrays)
print("\nMatrix Operations:")
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print("matrix1:\n", matrix1)
print("matrix2:\n", matrix2)

print("matrix1 + matrix2:\n", matrix1 + matrix2) # Element-wise addition
print("matrix1 @ matrix2:\n", matrix1 @ matrix2)  # Matrix multiplication (using @ operator)
print("np.dot(matrix1, matrix2):\n", np.dot(matrix1, matrix2)) # Matrix multiplication (using np.dot)
print("matrix1.T:\n", matrix1.T)  # Transpose of matrix1
print("np.linalg.inv(matrix1):\n", np.linalg.inv(matrix1))  # Inverse of matrix1 (if it exists)


# Reshaping and flattening
print("\nReshaping/Flattening:")
print("arr1.reshape(5, 1):\n", arr1.reshape(5, 1))  # Reshape to a column vector
print("arr2.flatten():", arr2.flatten())  # Flatten to a 1D array

# Concatenation
print("\nConcatenation:")
arr7 = np.array([7, 8, 9])
print("np.concatenate((arr1, arr7)):", np.concatenate((arr1, arr7))) # Concatenate along existing axis

# Boolean indexing
print("\nBoolean Indexing:")
print("arr1 > 3:", arr1 > 3)  # Returns a boolean array
print("arr1[arr1 > 3]:", arr1[arr1 > 3])  # Selects elements greater than 3

# Where function
print("\nWhere Function:")
print("np.where(arr1 > 3, arr1, 0):", np.where(arr1 > 3, arr1, 0)) # If condition is true, return element from arr1, else return 0

# Unique elements
print("\nUnique Elements:")
arr8 = np.array([1, 2, 2, 3, 3, 1, 4])
print("np.unique(arr8):", np.unique(arr8)) # Returns unique elements

arr1: [1 2 3 4 5]
arr2:
 [[1 2 3]
 [4 5 6]]
arr3:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
arr4:
 [[1. 1.]
 [1. 1.]]
arr5: [0 1 2 3 4 5 6 7 8 9]
arr6: [0.   0.25 0.5  0.75 1.  ]

Attributes:
arr1.ndim: 1
arr2.shape: (2, 3)
arr1.size: 5
arr1.dtype: int64

Basic Operations:
arr1 + 5: [ 6  7  8  9 10]
arr1 * 2: [ 2  4  6  8 10]
arr1 ** 2: [ 1  4  9 16 25]
np.sin(arr1): [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]

Aggregation:
np.sum(arr1): 15
np.mean(arr1): 3.0
np.max(arr2): 6
np.min(arr2): 1
np.std(arr1): 1.4142135623730951

Matrix Operations:
matrix1:
 [[1 2]
 [3 4]]
matrix2:
 [[5 6]
 [7 8]]
matrix1 + matrix2:
 [[ 6  8]
 [10 12]]
matrix1 @ matrix2:
 [[19 22]
 [43 50]]
np.dot(matrix1, matrix2):
 [[19 22]
 [43 50]]
matrix1.T:
 [[1 3]
 [2 4]]
np.linalg.inv(matrix1):
 [[-2.   1. ]
 [ 1.5 -0.5]]

Reshaping/Flattening:
arr1.reshape(5, 1):
 [[1]
 [2]
 [3]
 [4]
 [5]]
arr2.flatten(): [1 2 3 4 5 6]

Concatenation:
np.concatenate((arr1, arr7)): [1 2 3 4 5 7 8 9]

Boolean In